version: '3.8'

services:
  coupon-api:
    build: .
    container_name: coupon-api-app
    ports:
      - "8080:8080"
      - "8082:8082"
    environment:
      - SPRING_H2_CONSOLE_SETTINGS_WEB_ALLOW_OTHERS=true